import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "./globals.css";
import { Manrope, Space_Grotesk } from "next/font/google";
import {
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { theme } from "@/lib/theme";
import { QueryProvider } from "@/providers/QueryProvider";
import { AuthProvider } from "@/context/AuthContext";
import { SidebarWrapper } from "@/components/Sidebar/SidebarWrapper";
import { Suspense } from "react";
import { GoogleAnalytics } from "@/components/GoogleAnalytics/GoogleAnalytics";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Healink",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      {...mantineHtmlProps}
      className={`${manrope.variable} ${spaceGrotesk.variable}`}
    >
      <head>
      </head>
      <body style={{ width: "100%", minHeight: "100vh" }}>
        <QueryProvider>
          <AuthProvider>
            <MantineProvider theme={theme}>
              <div style={{ display: "flex", width: "100%", minHeight: "100vh" }}>
                <SidebarWrapper />
                <div style={{ flex: 1, minHeight: "100vh", overflow: "auto" }}>
                  <main style={{ minHeight: "100%", backgroundColor: "var(--mantine-color-gray-0)" }}>
                    {children}
                  </main>
                </div>
              </div>
            </MantineProvider>
          </AuthProvider>
        </QueryProvider>
        <Suspense fallback={null}>
          <GoogleAnalytics />
        </Suspense>
      </body>
    </html>

  );
}
